'\" t
.\"     Title: 
\fBxe host-cpu-param-get\fR    
.\"    Author: Jens Schweikhardt <schweikh@schweikhardt.net>
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 07/26/2012
.\"    Manual: User Manuals
.\"    Source: host-cpu-param-get 0.1.2
.\"  Language: English
.\"
.TH "\FBXE HOST\-CPU\-PA" "1" "07/26/2012" "host-cpu-param-get 0.1.2" "User Manuals"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
host-cpu-param-get \- Returns a parameter value for the host\*(Aqs CPU
.SH "SYNOPSIS"
.HP \w'\fBxe\ host\-cpu\-param\-get\ uuid=<uuid>\ param\-name=<parameter>[param\-key=<key>]\fR\ 'u
\fBxe host\-cpu\-param\-get uuid=<uuid> param\-name=<parameter>[param\-key=<key>]\fR
.SH "DESCRIPTION"
.PP

\fBxe host\-cpu\-param\-get\fR
gets the CPU parameters for a host\&.
.PP
To get the CPU model, type in this command:
\fBxe host\-cpu\-param\-get uuid=<uuid> param\-name=modelname\fR
.PP
To get the CPU speed, type in this command:
\fBxe host\-cpu\-param\-get uuid=<uuid> param\-name=speed\fR
.SH "OPTIONS"
.PP
\fBuuid\fR
.RS 4
The unique identifier for the CPU\&.
.RE
.PP
\fBparam\-name \fR
.RS 4
Parameter name\&.
.PP
\fBhost\-uuid\fR
.RS 4
The unique identifier/object reference for the host\&.
.RE
.PP
\fBnumber\fR
.RS 4
The number of physical CPU core within the host\&.
.RE
.PP
\fBvendor\fR
.RS 4
The vendor for the CPU\&.
.RE
.PP
\fBspeed\fR
.RS 4
The CPU clock speed in Hz\&.
.RE
.PP
\fBmodel\fR
.RS 4
The model number for the CPU\&.
.RE
.PP
\fBfamily\fR
.RS 4
The physical CPU family number\&.
.RE
.PP
\fBmodelname\fR
.RS 4
The CPU model\&.
.RE
.PP
\fBstepping\fR
.RS 4
The CPU revision number\&.
.RE
.PP
\fBflags\fR
.RS 4
CPU flags\&.
.RE
.PP
\fButilisation\fR
.RS 4
The current CPU utilisation\&.
.RE
.RE
.SH "EXAMPLES"
.PP
\fBxe host\-cpu\-param\-get uuid=<uuid> param\-name=modelname\fR
.RS 4
Returns the CPU model given its UUID\&.
.RE
.PP
\fBxe host\-cpu\-param\-get uuid=<uuid> param\-name=speed\fR
.RS 4
Returns the CPU speed in Hz given its UUID\&.
.RE
.SH "SEE ALSO"
.PP
\fBhost-cpu-list\fR(1),
\fBhost-cpu-param-list\fR(1)
.SH "AUTHORS"
.PP
\fBJens Schweikhardt\fR <\&schweikh@schweikhardt\&.net\&>
.RS 4
Wrote this example manpage for the "Linux Man Page Howto", available at \m[blue]\fB\%http://www.schweikhardt.net/man_page_howto.html\fR\m[] or \m[blue]\fB\%http://www.faqs.org/docs/Linux-mini/Man-Page.html\fR\m[]\&.
.RE
.PP
\fBDaniel Leidert\fR <\&daniel\&.leidert@wgdd\&.de\&>
.RS 4
Rewrote and extended the example manpage in DocBook XML for the Debian distribution\&.
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 1995-2003 Jens Schweikhardt
.br
Copyright \(co 2006 Daniel Leidert
.br
.PP
The Howto containing this example, was offered under the following conditions:
.PP
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  2." 4.2
.\}
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution\&.
.RE
.PP
THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED\&. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE\&.
.sp
